"""Dependency-free local browser UI for Paperazzi."""

APP_HTML = r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>Paperazzi</title>
<style>
:root{font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#17202a;background:#f5f7fa}
*{box-sizing:border-box}body{margin:0}button,input{font:inherit}button{cursor:pointer}a{color:inherit}
header{background:#101820;color:#fff;padding:15px 22px;display:flex;gap:15px;align-items:center;position:sticky;top:0;z-index:20}header h1{font-size:20px;margin:0}.search{display:flex;gap:7px;flex:1}.search input{width:100%;padding:9px 11px;border:0;border-radius:7px}.tabs{display:flex;gap:5px}.tabs button,.search button{border:0;border-radius:7px;padding:8px 11px}
main{max-width:1280px;margin:0 auto;padding:20px}.panel{background:#fff;border:1px solid #e2e7ec;border-radius:11px;box-shadow:0 2px 8px rgba(0,0,0,.04);overflow:visible}.toolbar{padding:14px 16px;border-bottom:1px solid #edf0f3;display:flex;justify-content:space-between;align-items:center;gap:10px}.toolbar-actions{display:flex;gap:7px;flex-wrap:wrap}.toolbar button{border:1px solid #ccd5dd;background:#fff;border-radius:7px;padding:7px 10px}.muted{color:#69737d}.list{display:grid}.row{padding:13px 16px;border-bottom:1px solid #edf0f3;display:grid;gap:5px;cursor:pointer}.row:hover{background:#f8fafc}.title{font-weight:650}.meta{font-size:13px;color:#69737d;display:flex;gap:9px;flex-wrap:wrap}.badge{display:inline-block;padding:2px 7px;border:1px solid #d5dce3;border-radius:999px;font-size:11px;background:#fafbfc}.badge.role{font-weight:700}.badge.warn{background:#fff6e8;border-color:#f0c989}.badge.ok{background:#eef8f0;border-color:#b8dabd}.badge.info{background:#eef5ff;border-color:#b8cee8}.detail{padding:20px}.detail h2{margin-top:0}.grid{display:grid;grid-template-columns:minmax(0,2fr) minmax(300px,1fr);gap:17px}.side{padding:16px}.stat{display:flex;justify-content:space-between;gap:10px;padding:7px 0;border-bottom:1px solid #edf0f3}.empty{padding:26px;color:#69737d;text-align:center}.error{padding:18px;color:#8b1e1e;background:#fff0f0}.pdf{display:inline-block;padding:7px 10px;background:#101820;color:#fff;border-radius:7px;text-decoration:none;font-size:13px}.back{cursor:pointer;color:#4b6577;margin-bottom:11px;display:inline-block}.section{margin-top:20px}.section h3{margin-bottom:8px}.author-line{padding:7px 0;border-bottom:1px dashed #e4e7eb}.author-link{font-weight:600;cursor:pointer;text-decoration:underline;text-decoration-style:dotted}
.pager{padding:10px 14px;display:flex;justify-content:center;align-items:center;gap:8px;border-bottom:1px solid #edf0f3;background:#fff}.pager.sticky{position:sticky;top:65px;z-index:12;box-shadow:0 2px 7px rgba(0,0,0,.05)}.pager.bottom{border-top:1px solid #edf0f3;border-bottom:0}.pager button{border:1px solid #ccd5dd;background:#fff;border-radius:7px;padding:6px 10px}.pager button:disabled{opacity:.4;cursor:default}.pager input{width:58px;padding:5px 7px;text-align:center;border:1px solid #ccd5dd;border-radius:6px}
.review-card{border:1px solid #dce3e9;border-radius:10px;padding:14px;margin:10px 0;background:#fff}.review-card.candidate{background:#fbfcfd}.review-card h3{margin:0 0 8px}.review-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:11px}.review-actions button{border:1px solid #bfcbd4;background:#fff;padding:7px 10px;border-radius:7px}.review-actions button.primary{background:#101820;color:#fff;border-color:#101820}.review-actions button.danger{border-color:#d99;color:#8b1e1e}.variant{display:inline-block;margin:2px 4px 2px 0;padding:2px 6px;background:#f1f4f6;border-radius:5px;font-size:12px}.paper-mini{font-size:12px;padding:3px 0;color:#4e5964}.explain{padding:10px 12px;background:#f7f9fb;border:1px solid #e2e8ee;border-radius:8px;font-size:13px;color:#51606b}.evidence-row{padding:9px 0;border-bottom:1px dashed #e3e8ed;font-size:13px}.evidence-row:last-child{border-bottom:0}.evidence-raw{white-space:pre-wrap;word-break:break-word;margin-top:4px;color:#3f4b55}
@media(max-width:850px){header{align-items:stretch;flex-direction:column}.grid{grid-template-columns:1fr}.tabs{order:3}.pager.sticky{top:154px}}
</style>
</head>
<body>
<header>
<h1>Paperazzi</h1>
<div class="search"><input id="q" placeholder="Search papers, authors, DOI, journal"/><button onclick="runSearch()">Search</button></div>
<div class="tabs"><button onclick="showPapers(0)">Papers</button><button onclick="showAuthors(0)">Authors</button><button onclick="showReviews()">Identity Review</button></div>
</header>
<main id="app"><div class="panel"><div class="empty">Loading…</div></div></main>
<script>
const app=document.getElementById('app'), PAGE_SIZE=100; let paperOffset=0,authorOffset=0;
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(url,opts={}){const r=await fetch(url,opts);let body=null;try{body=await r.json()}catch{}if(!r.ok)throw new Error(body?.detail||`${r.status} ${r.statusText}`);return body}
async function post(url,body={}){return api(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})}
function fail(e){app.innerHTML=`<div class="panel"><div class="error">${esc(e.message)}</div></div>`}
function pager(total,offset,kind,sticky=false){const page=Math.floor(offset/PAGE_SIZE)+1,pages=Math.max(1,Math.ceil(total/PAGE_SIZE)),prev=Math.max(0,offset-PAGE_SIZE),next=offset+PAGE_SIZE,fn=kind==='papers'?'showPapers':'showAuthors',id=`jump-${kind}-${sticky?'top':'bottom'}`;return `<div class="pager ${sticky?'sticky':'bottom'}"><button ${offset===0?'disabled':''} onclick="${fn}(${prev})">← Previous</button><span>Page</span><input id="${id}" type="number" min="1" max="${pages}" value="${page}" onkeydown="if(event.key==='Enter')jumpPage('${kind}','${id}',${pages})"><span>/ ${pages}</span><button onclick="jumpPage('${kind}','${id}',${pages})">Go</button><button ${next>=total?'disabled':''} onclick="${fn}(${next})">Next →</button></div>`}
function jumpPage(kind,id,pages){const n=Math.min(pages,Math.max(1,parseInt(document.getElementById(id).value||'1',10))),off=(n-1)*PAGE_SIZE;(kind==='papers'?showPapers:showAuthors)(off)}
function paperRow(p){const pdf=p.pdf?.available?'<span class="badge ok">PDF</span>':'<span class="badge">No local PDF</span>',first=p.first_author_resolved?'':' <span class="badge warn">identity unresolved</span>';return `<div class="row" onclick="showPaper(${p.paper_id})"><div class="title">${esc(p.title||'Untitled')}</div><div class="meta"><span>ID ${p.paper_id}</span><span>${esc(p.year||'')}</span><span>${esc(p.venue||'')}</span><span>First: ${esc(p.first_author||'Unknown')}${first}</span><span>${esc(p.author_count)} authors</span>${pdf}</div></div>`}
async function showPapers(offset=paperOffset){paperOffset=Math.max(0,offset);try{const d=await api(`/api/papers?limit=${PAGE_SIZE}&offset=${paperOffset}`);app.innerHTML=`<div class="panel"><div class="toolbar"><strong>Papers</strong><span class="muted">${d.total} in Zotero</span></div>${pager(d.total,paperOffset,'papers',true)}<div class="list">${d.items.map(paperRow).join('')||'<div class="empty">No papers</div>'}</div>${pager(d.total,paperOffset,'papers')}</div>`}catch(e){fail(e)}}
function authorRow(a){const pri=a.enrichment_priority?'<span class="badge ok">priority enrichment</span>':'';return `<div class="row" onclick="showAuthor('${encodeURIComponent(a.author_id)}')"><div class="title">${esc(a.preferred_name||a.author_id)}</div><div class="meta"><span>${a.paper_count} papers</span><span>${a.first_author_count} first-author</span><span>${a.corresponding_author_count} corresponding</span>${pri}</div></div>`}
async function showAuthors(offset=authorOffset){authorOffset=Math.max(0,offset);try{const d=await api(`/api/authors?limit=${PAGE_SIZE}&offset=${authorOffset}`);app.innerHTML=`<div class="panel"><div class="toolbar"><strong>Canonical authors</strong><span class="muted">${d.total} resolved identities</span></div>${pager(d.total,authorOffset,'authors',true)}<div class="list">${d.items.map(authorRow).join('')||'<div class="empty">No authors</div>'}</div>${pager(d.total,authorOffset,'authors')}</div>`}catch(e){fail(e)}}
async function showPaper(id){try{const p=await api('/api/papers/'+id),auth=p.authors.map(a=>{const name=a.author_id?`<span class="author-link" onclick="showAuthor('${encodeURIComponent(a.author_id)}')">${esc(a.preferred_name||a.source_name)}</span>`:esc(a.source_name),roles=a.roles.map(r=>`<span class="badge role">${esc(r)}</span>`).join(' '),unresolved=a.identity_status==='UNRESOLVED'?'<span class="badge warn" title="The source author name is known, but this paper-author mention has not yet been safely linked to a canonical author identity.">IDENTITY UNRESOLVED</span>':'';return `<div class="author-line">${a.order_index+1}. ${name} ${roles} ${unresolved}<div class="meta">source: ${esc(a.source_name)}</div></div>`}).join(''),pdf=p.pdf?.available?`<a class="pdf" target="_blank" href="/api/papers/${p.paper_id}/pdf">Open local PDF</a>`:'<span class="muted">Local PDF unavailable</span>';app.innerHTML=`<div class="back" onclick="showPapers()">← Papers</div><div class="grid"><div class="panel detail"><h2>${esc(p.title||'Untitled')}</h2><div class="meta"><span><b>Paperazzi ID ${p.paper_id}</b></span><span>${esc(p.year||'')}</span><span>${esc(p.venue||'')}</span><span>${esc(p.doi||'No DOI')}</span></div><div class="section"><h3>All source authors</h3><div class="explain">Source names are retained exactly as bibliographic records. Canonical identity is an additional link; it never overwrites a sourced spelling.</div>${auth||'<div class="muted">No source authors</div>'}</div><div class="section">${pdf}</div></div><div class="panel side"><h3>Paper</h3><div class="stat"><span>Paperazzi ID</span><strong>${p.paper_id}</strong></div><div class="stat"><span>Authors</span><strong>${p.author_count}</strong></div><div class="stat"><span>PDF</span><strong>${esc(p.pdf?.status||'NONE')}</strong></div><div class="stat"><span>Document role</span><strong>${esc(p.pdf?.role||'UNKNOWN')}</strong></div></div></div>`}catch(e){fail(e)}}
async function showAuthor(encoded){try{const [a,evidence]=await Promise.all([api('/api/authors/'+encoded),api('/api/authors/'+encoded+'/evidence?limit=50')]),pubs=a.publications.map(p=>`<div class="row" onclick="showPaper(${p.paper_id})"><div class="title">${esc(p.title||'Untitled')}</div><div class="meta"><span>ID ${p.paper_id}</span><span>${esc(p.year||'')}</span><span>${p.roles.map(r=>`<span class="badge role">${esc(r)}</span>`).join(' ')}</span></div></div>`).join(''),co=a.coauthors.slice(0,20).map(c=>`<div class="stat"><span class="author-link" onclick="showAuthor('${encodeURIComponent(c.author_id)}')">${esc(c.preferred_name||c.author_id)}</span><strong>${c.shared_papers}</strong></div>`).join(''),variants=(a.name_variants||[]).map(v=>`<span class="variant" title="${esc(v.provenance||'')}">${esc(v.raw_name)}</span>`).join(''),evidenceRows=(evidence||[]).map(e=>`<div class="evidence-row"><div><span class="badge ${e.status==='ACCEPTED'?'ok':'warn'}">${esc(e.status)}</span> <b>${esc(e.evidence_type)}</b></div><div class="meta"><span>paper ${e.paper_id}</span><span>${esc(e.year||'')}</span><span class="author-link" onclick="showPaper(${e.paper_id})">${esc(e.paper_title||'Untitled')}</span></div><div class="evidence-raw">${esc(e.raw_value||'')}</div></div>`).join('');app.innerHTML=`<div class="back" onclick="showAuthors()">← Authors</div><div class="grid"><div class="panel"><div class="detail"><h2>${esc(a.preferred_name||a.author_id)}</h2><div class="meta"><span>${esc(a.author_id)}</span>${a.enrichment_priority?'<span class="badge ok">priority enrichment</span>':''}</div><div class="section"><h3>Recorded name variants</h3>${variants||'<span class="muted">No variants recorded</span>'}<div class="explain">Abbreviations, hyphenation and other sourced spellings remain separate records even when they are grouped into one canonical identity.</div></div><div class="section"><h3>Sourced affiliation / contact evidence</h3><div class="explain">These are provenance-bearing paper-level observations. CANDIDATE evidence is not a verified current affiliation, and this view does not promote it into a canonical profile field.</div>${evidenceRows||'<div class="muted">No current sourced affiliation/contact evidence.</div>'}</div></div><div class="list">${pubs||'<div class="empty">No publications</div>'}</div></div><div class="panel side"><h3>Profile</h3><div class="stat"><span>Papers</span><strong>${a.paper_count}</strong></div><div class="stat"><span>First author</span><strong>${a.first_author_count}</strong></div><div class="stat"><span>Corresponding</span><strong>${a.corresponding_author_count}</strong></div><div class="section"><h3>Top coauthors</h3>${co||'<div class="muted">None resolved</div>'}</div></div></div>`}catch(e){fail(e)}}
async function refreshSimilar(){try{const r=await post('/api/reviews/identity/sync-name-variants');const s=await post('/api/reviews/identity/refresh-similar');alert(`Name variants added: ${r.variants_added}\nSimilar-name reviews refreshed: ${s.reviews_created_or_updated}`);showReviews()}catch(e){alert(e.message)}}
async function showReviews(){try{const rows=await api('/api/reviews/identity?limit=300');app.innerHTML=`<div class="panel"><div class="toolbar"><div><strong>Identity Review</strong><div class="muted">Source names stay intact. Review only controls canonical-person grouping.</div></div><div class="toolbar-actions"><button onclick="refreshSimilar()">Refresh similar names</button></div></div><div class="list">${rows.map(r=>`<div class="row" onclick="showIdentityReview(${r.review_item_id})"><div class="title">${esc(r.source_name||r.subject_id)}</div><div class="meta"><span>${esc(r.queue_type)}</span><span>${esc(r.reason_code||'')}</span><span>priority ${r.effective_priority}</span>${r.paper_id?`<span>paper ${r.paper_id}</span>`:''}<span>Review →</span></div></div>`).join('')||'<div class="empty">No open identity review items. Use “Refresh similar names” to scan canonical identities for abbreviation/hyphenation variants.</div>'}</div></div>`}catch(e){fail(e)}}
function authorCompareCard(a,label){const vars=(a.variants||[]).map(v=>`<span class="variant">${esc(v.raw_name)}</span>`).join(''),papers=(a.papers||[]).map(p=>`<div class="paper-mini">ID ${p.paper_id} · ${esc(p.year||'')} · ${esc(p.title||'Untitled')}</div>`).join(''),co=(a.coauthors||[]).map(c=>esc(c.preferred_name)).join(', ');return `<div class="review-card candidate"><h3>${esc(label)}: ${esc(a.preferred_name||a.author_id)}</h3><div class="meta"><span>${esc(a.author_id)}</span>${a.similarity_score!=null?`<span>similarity ${Number(a.similarity_score).toFixed(2)}</span>`:''}${a.same_paper_conflict?'<span class="badge warn">same-paper conflict</span>':''}</div><div><b>Names:</b> ${vars||'—'}</div><div class="section"><b>Recent papers</b>${papers||'<div class="muted">None</div>'}</div><div class="paper-mini"><b>Coauthors:</b> ${co||'—'}</div></div>`}
async function linkCandidate(reviewId,authorId){if(!confirm('Link this source author mention to the selected canonical author? The source spelling will be retained as a name variant.'))return;try{await post(`/api/reviews/identity/${reviewId}/link`,{target_author_id:authorId,notes:'Manual Identity Review UI'});showReviews()}catch(e){alert(e.message)}}
async function notSame(reviewId,authorId){if(!confirm('Record that this source mention is NOT the same person as this candidate?'))return;try{await post(`/api/reviews/identity/${reviewId}/not-same`,{candidate_author_id:authorId,notes:'Manual Identity Review UI'});showIdentityReview(reviewId)}catch(e){alert(e.message)}}
async function createSeparate(reviewId){if(!confirm('Create a separate canonical identity for this source mention?'))return;try{await post(`/api/reviews/identity/${reviewId}/create-identity`,{notes:'Manual Identity Review UI'});showReviews()}catch(e){alert(e.message)}}
async function mergePair(source,target,reviewId){if(!confirm('Merge these two canonical identities? All source name variants and paper memberships will be retained under the target identity. Same-paper co-occurrence is blocked automatically.'))return;try{await post('/api/authors/merge',{source_author_id:source,target_author_id:target,review_item_id:reviewId,notes:'Manual Identity Review UI'});showReviews()}catch(e){alert(e.message)}}
async function showIdentityReview(id){try{const d=await api('/api/reviews/identity/'+id);if(d.subject_type==='creator_mention'){const m=d.source_mention,cards=(d.candidates||[]).map(a=>`${authorCompareCard(a,'Candidate')}<div class="review-actions"><button class="primary" ${a.same_paper_conflict?'disabled':''} onclick="linkCandidate(${id},'${esc(a.author_id)}')">Link mention to this identity</button><button class="danger" onclick="notSame(${id},'${esc(a.author_id)}')">Not same person</button><button onclick="showAuthor('${encodeURIComponent(a.author_id)}')">Open full profile</button></div>`).join('');app.innerHTML=`<div class="back" onclick="showReviews()">← Identity Review</div><div class="panel detail"><h2>Compare source mention</h2><div class="review-card"><h3>${esc(m.source_name)}</h3><div class="meta"><span>Paperazzi paper ID ${m.paper_id}</span><span>author position ${m.order_index+1}</span><span>${esc(d.reason_code||'')}</span></div><div class="paper-mini">${esc(m.paper_title||'')}</div></div><div class="explain">Similarity is a review aid only. A name match never auto-merges people. Compare name variants, publications and coauthors before linking.</div>${cards||'<div class="empty">No similar canonical author candidates found.</div>'}<div class="review-actions"><button onclick="createSeparate(${id})">Create separate identity</button></div></div>`}else if(d.subject_type==='author'&&d.source_author){const left=d.source_author,right=(d.candidates||[])[0];app.innerHTML=`<div class="back" onclick="showReviews()">← Identity Review</div><div class="panel detail"><h2>Possible duplicate canonical identities</h2><div class="explain">This is a manual merge decision. Source name variants are preserved; same-paper co-occurrence blocks a merge.</div>${authorCompareCard(left,'Identity A')}${right?authorCompareCard(right,'Identity B'):'<div class="empty">Candidate missing</div>'}${right?`<div class="review-actions"><button class="primary" onclick="mergePair('${esc(left.author_id)}','${esc(right.author_id)}',${id})">Merge A → B</button><button class="primary" onclick="mergePair('${esc(right.author_id)}','${esc(left.author_id)}',${id})">Merge B → A</button></div>`:''}</div>`}else{app.innerHTML=`<div class="back" onclick="showReviews()">← Identity Review</div><div class="panel detail"><h2>${esc(d.queue_type)}</h2><pre>${esc(JSON.stringify(d,null,2))}</pre></div>`}}catch(e){fail(e)}}
async function runSearch(){const q=document.getElementById('q').value.trim();if(!q){showPapers(0);return}try{const d=await api('/api/search?q='+encodeURIComponent(q)+'&limit=50');app.innerHTML=`<div class="grid"><div class="panel"><div class="toolbar"><strong>Papers</strong><span class="muted">${d.papers.length} shown</span></div><div class="list">${d.papers.map(paperRow).join('')||'<div class="empty">No paper matches</div>'}</div></div><div class="panel"><div class="toolbar"><strong>Authors</strong><span class="muted">${d.authors.length} shown</span></div><div class="list">${d.authors.map(authorRow).join('')||'<div class="empty">No author matches</div>'}</div></div></div>`}catch(e){fail(e)}}
document.getElementById('q').addEventListener('keydown',e=>{if(e.key==='Enter')runSearch()});showPapers(0);
</script>
</body>
</html>'''
