"""Minimal dependency-free browser UI for the Phase 5 MVP."""

APP_HTML = r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>Paperazzi</title>
<style>
:root{font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#17202a;background:#f5f7fa}
*{box-sizing:border-box} body{margin:0} a{color:inherit} button,input{font:inherit}
header{background:#101820;color:white;padding:18px 24px;display:flex;gap:18px;align-items:center;position:sticky;top:0;z-index:10}
header h1{font-size:20px;margin:0;letter-spacing:.04em}.search{flex:1;display:flex;gap:8px}.search input{width:100%;padding:10px 12px;border-radius:8px;border:0}.search button,.tabs button{border:0;border-radius:8px;padding:9px 12px;cursor:pointer}.tabs{display:flex;gap:6px}
main{max-width:1280px;margin:0 auto;padding:22px}.panel{background:white;border:1px solid #e2e7ec;border-radius:12px;box-shadow:0 2px 8px rgba(0,0,0,.04);overflow:hidden}.toolbar{padding:16px;border-bottom:1px solid #edf0f3;display:flex;justify-content:space-between;align-items:center}.muted{color:#69737d}.list{display:grid}.row{padding:14px 16px;border-bottom:1px solid #edf0f3;display:grid;gap:5px;cursor:pointer}.row:hover{background:#f8fafc}.row:last-child{border-bottom:0}.title{font-weight:650}.meta{font-size:13px;color:#69737d;display:flex;gap:10px;flex-wrap:wrap}.badge{display:inline-block;padding:2px 7px;border:1px solid #d5dce3;border-radius:999px;font-size:11px;background:#fafbfc}.badge.role{font-weight:700}.badge.warn{background:#fff6e8;border-color:#f0c989}.badge.ok{background:#eef8f0;border-color:#b8dabd}.detail{padding:20px}.detail h2{margin-top:0}.author-line{padding:7px 0;border-bottom:1px dashed #e4e7eb}.author-line:last-child{border:0}.author-link{font-weight:600;cursor:pointer;text-decoration:underline;text-decoration-style:dotted}.grid{display:grid;grid-template-columns:minmax(0,2fr) minmax(280px,1fr);gap:18px}.side{padding:16px}.side h3{margin:4px 0 12px}.stat{display:flex;justify-content:space-between;padding:7px 0;border-bottom:1px solid #edf0f3}.empty{padding:28px;color:#69737d;text-align:center}.error{padding:20px;color:#8b1e1e;background:#fff0f0}.pdf{display:inline-block;padding:7px 10px;background:#101820;color:#fff;border-radius:7px;text-decoration:none;font-size:13px}.back{cursor:pointer;color:#4b6577;margin-bottom:12px;display:inline-block}.section{margin-top:22px}.section h3{margin-bottom:8px}@media(max-width:800px){header{align-items:stretch;flex-direction:column}.grid{grid-template-columns:1fr}.tabs{order:3}}
</style>
</head>
<body>
<header>
<h1>Paperazzi</h1>
<div class="search"><input id="q" placeholder="Search papers, authors, DOI, journal"/><button onclick="runSearch()">Search</button></div>
<div class="tabs"><button onclick="showPapers()">Papers</button><button onclick="showAuthors()">Authors</button><button onclick="showReviews()">Identity Review</button></div>
</header>
<main id="app"><div class="panel"><div class="empty">Loading…</div></div></main>
<script>
const app=document.getElementById('app');
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(url){const r=await fetch(url);if(!r.ok)throw new Error((await r.json().catch(()=>({}))).detail||`${r.status} ${r.statusText}`);return r.json()}
function fail(e){app.innerHTML=`<div class="panel"><div class="error">${esc(e.message)}</div></div>`}
function paperRow(p){const pdf=p.pdf?.available?'<span class="badge ok">PDF</span>':'<span class="badge">No local PDF</span>';const first=p.first_author_resolved?'':' <span class="badge warn">identity unresolved</span>';return `<div class="row" onclick="showPaper(${p.paper_id})"><div class="title">${esc(p.title||'Untitled')}</div><div class="meta"><span>${esc(p.year||'')}</span><span>${esc(p.venue||'')}</span><span>First: ${esc(p.first_author||'Unknown')}${first}</span><span>${esc(p.author_count)} authors</span>${pdf}</div></div>`}
async function showPapers(){try{const d=await api('/api/papers?limit=100');app.innerHTML=`<div class="panel"><div class="toolbar"><strong>Papers</strong><span class="muted">${d.total} in Zotero</span></div><div class="list">${d.items.map(paperRow).join('')||'<div class="empty">No papers</div>'}</div></div>`}catch(e){fail(e)}}
function authorRow(a){const pri=a.enrichment_priority?'<span class="badge ok">priority enrichment</span>':'';return `<div class="row" onclick="showAuthor('${encodeURIComponent(a.author_id)}')"><div class="title">${esc(a.preferred_name||a.author_id)}</div><div class="meta"><span>${a.paper_count} papers</span><span>${a.first_author_count} first-author</span><span>${a.corresponding_author_count} corresponding</span>${pri}</div></div>`}
async function showAuthors(){try{const d=await api('/api/authors?limit=100');app.innerHTML=`<div class="panel"><div class="toolbar"><strong>Canonical authors</strong><span class="muted">${d.total} resolved identities</span></div><div class="list">${d.items.map(authorRow).join('')||'<div class="empty">No authors</div>'}</div></div>`}catch(e){fail(e)}}
async function showPaper(id){try{const p=await api('/api/papers/'+id);const auth=p.authors.map(a=>{const name=a.author_id?`<span class="author-link" onclick="event.stopPropagation();showAuthor('${encodeURIComponent(a.author_id)}')">${esc(a.preferred_name||a.source_name)}</span>`:esc(a.source_name);const roles=a.roles.map(r=>`<span class="badge role">${esc(r)}</span>`).join(' ');const unresolved=a.identity_status==='UNRESOLVED'?'<span class="badge warn">UNRESOLVED</span>':'';return `<div class="author-line">${a.order_index+1}. ${name} ${roles} ${unresolved}</div>`}).join('');const pdf=p.pdf?.available?`<a class="pdf" target="_blank" href="/api/papers/${p.paper_id}/pdf">Open local PDF</a>`:'<span class="muted">Local PDF unavailable</span>';app.innerHTML=`<div class="back" onclick="showPapers()">← Papers</div><div class="grid"><div class="panel detail"><h2>${esc(p.title||'Untitled')}</h2><div class="meta"><span>${esc(p.year||'')}</span><span>${esc(p.venue||'')}</span><span>${esc(p.doi||'No DOI')}</span></div><div class="section"><h3>All authors</h3>${auth||'<div class="muted">No source authors</div>'}</div><div class="section">${pdf}</div></div><div class="panel side"><h3>Paper</h3><div class="stat"><span>Authors</span><strong>${p.author_count}</strong></div><div class="stat"><span>First author resolved</span><strong>${p.first_author_resolved?'yes':'no'}</strong></div><div class="stat"><span>PDF</span><strong>${esc(p.pdf?.status||'NONE')}</strong></div></div></div>`}catch(e){fail(e)}}
async function showAuthor(encoded){try{const a=await api('/api/authors/'+encoded);const pubs=a.publications.map(p=>`<div class="row" onclick="showPaper(${p.paper_id})"><div class="title">${esc(p.title||'Untitled')}</div><div class="meta"><span>${esc(p.year||'')}</span><span>${esc(p.venue||'')}</span><span>${p.roles.map(r=>`<span class="badge role">${esc(r)}</span>`).join(' ')}</span></div></div>`).join('');const co=a.coauthors.slice(0,20).map(c=>`<div class="stat"><span class="author-link" onclick="showAuthor('${encodeURIComponent(c.author_id)}')">${esc(c.preferred_name||c.author_id)}</span><strong>${c.shared_papers}</strong></div>`).join('');app.innerHTML=`<div class="back" onclick="showAuthors()">← Authors</div><div class="grid"><div class="panel"><div class="detail"><h2>${esc(a.preferred_name||a.author_id)}</h2><div class="meta"><span>${esc(a.author_id)}</span>${a.enrichment_priority?'<span class="badge ok">priority enrichment</span>':''}</div></div><div class="list">${pubs||'<div class="empty">No publications</div>'}</div></div><div class="panel side"><h3>Profile</h3><div class="stat"><span>Papers</span><strong>${a.paper_count}</strong></div><div class="stat"><span>First author</span><strong>${a.first_author_count}</strong></div><div class="stat"><span>Corresponding</span><strong>${a.corresponding_author_count}</strong></div><div class="section"><h3>Top coauthors</h3>${co||'<div class="muted">None resolved</div>'}</div></div></div>`}catch(e){fail(e)}}
async function showReviews(){try{const rows=await api('/api/reviews/identity?limit=200');app.innerHTML=`<div class="panel"><div class="toolbar"><strong>Identity review</strong><span class="muted">priority: corresponding → first → ordinary</span></div><div class="list">${rows.map(r=>`<div class="row"><div class="title">${esc(r.source_name||r.subject_id)}</div><div class="meta"><span>${esc(r.queue_type)}</span><span>${esc(r.reason_code||'')}</span><span>priority ${r.effective_priority}</span>${r.paper_id?`<span class="author-link" onclick="showPaper(${r.paper_id})">paper ${r.paper_id}</span>`:''}</div></div>`).join('')||'<div class="empty">No open identity review items</div>'}</div></div>`}catch(e){fail(e)}}
async function runSearch(){const q=document.getElementById('q').value.trim();if(!q){showPapers();return}try{const d=await api('/api/search?q='+encodeURIComponent(q)+'&limit=50');app.innerHTML=`<div class="grid"><div class="panel"><div class="toolbar"><strong>Papers</strong><span class="muted">${d.papers.length} shown</span></div><div class="list">${d.papers.map(paperRow).join('')||'<div class="empty">No paper matches</div>'}</div></div><div class="panel"><div class="toolbar"><strong>Authors</strong><span class="muted">${d.authors.length} shown</span></div><div class="list">${d.authors.map(authorRow).join('')||'<div class="empty">No author matches</div>'}</div></div></div>`}catch(e){fail(e)}}
document.getElementById('q').addEventListener('keydown',e=>{if(e.key==='Enter')runSearch()});showPapers();
</script>
</body>
</html>'''
